### ISSUE TITLE
System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by iamcc** [zhangtaii/react-native-advanced-webview#2]
> System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
System.err: 	at im.shimo.react.webview.AdvancedWebViewManager$AdvancedWebView.linkBridge(AdvancedWebViewManager.java:280)
System.err: 	at im.shimo.react.webview.AdvancedWebViewManager$AdvancedWebViewClient.onPageFinished(AdvancedWebViewManager.java:676)
System.err: 	at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:199)
System.err: 	at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:67)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:148)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5426)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)

**Comment by AlanHilal** [comment]
have the same problem. have you found any solution?

**Comment by AlanHilal** [comment]
It turned out the website I was trying to cache was sending "Cache-Control = private" in the response header. I changed the value Cache-Control to "max-age:600". It solved the problem but there should be a case for the value to be null.
